apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "datapower-operator.namespacedname" . }}
  labels:
    app.kubernetes.io/instance: {{ template "datapower-operator.namespacedname" . }}
    app.kubernetes.io/name: datapower-operator
    app.kubernetes.io/managed-by: datapower-operator
